# Generated by Django 2.0 on 2019-11-28 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15, verbose_name='课程名')),
                ('periods', models.CharField(blank=True, max_length=30, null=True, verbose_name='学时')),
                ('credits', models.CharField(default='2', max_length=15, verbose_name='学分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程名',
                'verbose_name_plural': '课程名',
            },
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grade', to='performance.Course', verbose_name='课程名')),
            ],
            options={
                'verbose_name': '班级课程表',
                'verbose_name_plural': '班级课程表',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15, verbose_name='班级名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '班级序号',
                'verbose_name_plural': '班级序号',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_num', models.CharField(blank=True, max_length=45, null=True, verbose_name='成绩')),
                ('term', models.CharField(default='第一学期', max_length=15, verbose_name='学期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '班级课程表',
                'verbose_name_plural': '班级课程表',
            },
        ),
        migrations.CreateModel(
            name='PerformanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='类型名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '班级课程表',
                'verbose_name_plural': '班级课程表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15, verbose_name='名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True, verbose_name='学号')),
                ('name', models.CharField(default='匿名', max_length=15, verbose_name='名称')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('project', models.CharField(blank=True, max_length=45, null=True, verbose_name='专业')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('college', models.CharField(blank=True, max_length=45, null=True, verbose_name='学院')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='performance.Grade', verbose_name='班级')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='performance.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15, verbose_name='教师名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('project', models.CharField(blank=True, max_length=45, null=True, verbose_name='专业')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('college', models.CharField(blank=True, max_length=45, null=True, verbose_name='学院')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='performance.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.Student', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='performance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.PerformanceType', verbose_name='类型名'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='performance.Teacher', verbose_name='辅导员'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grade', to='performance.Grade', verbose_name='班级名'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='performance.Teacher', verbose_name='科任老师'),
        ),
    ]
