# Generated by Django 2.0 on 2019-11-28 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name': '成绩', 'verbose_name_plural': '成绩'},
        ),
        migrations.AlterModelOptions(
            name='performancetype',
            options={'verbose_name': '成绩类型', 'verbose_name_plural': '成绩类型'},
        ),
        migrations.AddField(
            model_name='performance',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
