# Generated by Django 2.0 on 2019-11-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20191128_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='performance.Student', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='role',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='performance.Teacher', verbose_name='教师'),
        ),
    ]
