# Generated by Django 2.0 on 2019-11-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20191128_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='student',
        ),
        migrations.RemoveField(
            model_name='role',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='performance.Role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='performance.Role', verbose_name='角色'),
        ),
    ]
