# Generated by Django 2.0 on 2019-12-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20191128_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.PerformanceType', verbose_name='类型名'),
        ),
    ]
