# Generated by Django 2.0 on 2019-12-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20191202_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='term',
            field=models.CharField(choices=[('one', '第一学期'), ('two', '第二学期')], default='one', max_length=15, verbose_name='学期'),
        ),
    ]
